name: Uses Examples

on:
  workflow_dispatch:   

jobs:
  uses-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run my_script.py
        run: python my_script.py
